package org.cloud.core;

public enum CommandType {
    AUTH,
    AUTH_OK,
    AUTH_TIME_OUT,
    REG,
    ERROR,
    LIST_FILE_REQUEST,
    LIST_FILE_RESPONSE,
    SPACE_REQUEST,
    SPACE_RESPONSE,
    SHARE_FILE,
    SHARE_FILE_RESPONSE,
    GET_SHARE_FILE,
    SEND_FILE,
    SENDER_FILE,
    DISCARD_FILE,
    SEND_FILE_APPROVE,
    PREPARE_SEND_FILE,
    DELETE_FILE,
    MESSAGE
}
